using System;
using System.Collections.Generic;

namespace VFDP.Models
{
    public partial class DcpParameterHis
    {
        public string Tid { get; set; }
        public string ParaNm { get; set; }
        public string ParaTyp { get; set; }
        public decimal StartIdx { get; set; }
        public DateTime CrtTm { get; set; }
        public string Data001 { get; set; }
        public string Data002 { get; set; }
        public string Data003 { get; set; }
        public string Data004 { get; set; }
        public string Data005 { get; set; }
        public string Data006 { get; set; }
        public string Data007 { get; set; }
        public string Data008 { get; set; }
        public string Data009 { get; set; }
        public string Data010 { get; set; }
        public string Data011 { get; set; }
        public string Data012 { get; set; }
        public string Data013 { get; set; }
        public string Data014 { get; set; }
        public string Data015 { get; set; }
        public string Data016 { get; set; }
        public string Data017 { get; set; }
        public string Data018 { get; set; }
        public string Data019 { get; set; }
        public string Data020 { get; set; }
        public string Data021 { get; set; }
        public string Data022 { get; set; }
        public string Data023 { get; set; }
        public string Data024 { get; set; }
        public string Data025 { get; set; }
        public string Data026 { get; set; }
        public string Data027 { get; set; }
        public string Data028 { get; set; }
        public string Data029 { get; set; }
        public string Data030 { get; set; }
        public string Data031 { get; set; }
        public string Data032 { get; set; }
        public string Data033 { get; set; }
        public string Data034 { get; set; }
        public string Data035 { get; set; }
        public string Data036 { get; set; }
        public string Data037 { get; set; }
        public string Data038 { get; set; }
        public string Data039 { get; set; }
        public string Data040 { get; set; }
        public string Data041 { get; set; }
        public string Data042 { get; set; }
        public string Data043 { get; set; }
        public string Data044 { get; set; }
        public string Data045 { get; set; }
        public string Data046 { get; set; }
        public string Data047 { get; set; }
        public string Data048 { get; set; }
        public string Data049 { get; set; }
        public string Data050 { get; set; }
        public string Data051 { get; set; }
        public string Data052 { get; set; }
        public string Data053 { get; set; }
        public string Data054 { get; set; }
        public string Data055 { get; set; }
        public string Data056 { get; set; }
        public string Data057 { get; set; }
        public string Data058 { get; set; }
        public string Data059 { get; set; }
        public string Data060 { get; set; }
        public string Data061 { get; set; }
        public string Data062 { get; set; }
        public string Data063 { get; set; }
        public string Data064 { get; set; }
        public string Data065 { get; set; }
        public string Data066 { get; set; }
        public string Data067 { get; set; }
        public string Data068 { get; set; }
        public string Data069 { get; set; }
        public string Data070 { get; set; }
        public string Data071 { get; set; }
        public string Data072 { get; set; }
        public string Data073 { get; set; }
        public string Data074 { get; set; }
        public string Data075 { get; set; }
        public string Data076 { get; set; }
        public string Data077 { get; set; }
        public string Data078 { get; set; }
        public string Data079 { get; set; }
        public string Data080 { get; set; }
        public string Data081 { get; set; }
        public string Data082 { get; set; }
        public string Data083 { get; set; }
        public string Data084 { get; set; }
        public string Data085 { get; set; }
        public string Data086 { get; set; }
        public string Data087 { get; set; }
        public string Data088 { get; set; }
        public string Data089 { get; set; }
        public string Data090 { get; set; }
        public string Data091 { get; set; }
        public string Data092 { get; set; }
        public string Data093 { get; set; }
        public string Data094 { get; set; }
        public string Data095 { get; set; }
        public string Data096 { get; set; }
        public string Data097 { get; set; }
        public string Data098 { get; set; }
        public string Data099 { get; set; }
        public string Data100 { get; set; }
        public string Data101 { get; set; }
        public string Data102 { get; set; }
        public string Data103 { get; set; }
        public string Data104 { get; set; }
        public string Data105 { get; set; }
        public string Data106 { get; set; }
        public string Data107 { get; set; }
        public string Data108 { get; set; }
        public string Data109 { get; set; }
        public string Data110 { get; set; }
        public string Data111 { get; set; }
        public string Data112 { get; set; }
        public string Data113 { get; set; }
        public string Data114 { get; set; }
        public string Data115 { get; set; }
        public string Data116 { get; set; }
        public string Data117 { get; set; }
        public string Data118 { get; set; }
        public string Data119 { get; set; }
        public string Data120 { get; set; }
        public string Data121 { get; set; }
        public string Data122 { get; set; }
        public string Data123 { get; set; }
        public string Data124 { get; set; }
        public string Data125 { get; set; }
        public string Data126 { get; set; }
        public string Data127 { get; set; }
        public string Data128 { get; set; }
        public string Data129 { get; set; }
        public string Data130 { get; set; }
        public string Data131 { get; set; }
        public string Data132 { get; set; }
        public string Data133 { get; set; }
        public string Data134 { get; set; }
        public string Data135 { get; set; }
        public string Data136 { get; set; }
        public string Data137 { get; set; }
        public string Data138 { get; set; }
        public string Data139 { get; set; }
        public string Data140 { get; set; }
        public string Data141 { get; set; }
        public string Data142 { get; set; }
        public string Data143 { get; set; }
        public string Data144 { get; set; }
        public string Data145 { get; set; }
        public string Data146 { get; set; }
        public string Data147 { get; set; }
        public string Data148 { get; set; }
        public string Data149 { get; set; }
        public string Data150 { get; set; }
        public string Data151 { get; set; }
        public string Data152 { get; set; }
        public string Data153 { get; set; }
        public string Data154 { get; set; }
        public string Data155 { get; set; }
        public string Data156 { get; set; }
        public string Data157 { get; set; }
        public string Data158 { get; set; }
        public string Data159 { get; set; }
        public string Data160 { get; set; }
        public string Data161 { get; set; }
        public string Data162 { get; set; }
        public string Data163 { get; set; }
        public string Data164 { get; set; }
        public string Data165 { get; set; }
        public string Data166 { get; set; }
        public string Data167 { get; set; }
        public string Data168 { get; set; }
        public string Data169 { get; set; }
        public string Data170 { get; set; }
        public string Data171 { get; set; }
        public string Data172 { get; set; }
        public string Data173 { get; set; }
        public string Data174 { get; set; }
        public string Data175 { get; set; }
        public string Data176 { get; set; }
        public string Data177 { get; set; }
        public string Data178 { get; set; }
        public string Data179 { get; set; }
        public string Data180 { get; set; }
        public string Data181 { get; set; }
        public string Data182 { get; set; }
        public string Data183 { get; set; }
        public string Data184 { get; set; }
        public string Data185 { get; set; }
        public string Data186 { get; set; }
        public string Data187 { get; set; }
        public string Data188 { get; set; }
        public string Data189 { get; set; }
        public string Data190 { get; set; }
        public string Data191 { get; set; }
        public string Data192 { get; set; }
        public string Data193 { get; set; }
        public string Data194 { get; set; }
        public string Data195 { get; set; }
        public string Data196 { get; set; }
        public string Data197 { get; set; }
        public string Data198 { get; set; }
        public string Data199 { get; set; }
        public string Data200 { get; set; }
        public string Data201 { get; set; }
        public string Data202 { get; set; }
        public string Data203 { get; set; }
        public string Data204 { get; set; }
        public string Data205 { get; set; }
        public string Data206 { get; set; }
        public string Data207 { get; set; }
        public string Data208 { get; set; }
        public string Data209 { get; set; }
        public string Data210 { get; set; }
        public string Data211 { get; set; }
        public string Data212 { get; set; }
        public string Data213 { get; set; }
        public string Data214 { get; set; }
        public string Data215 { get; set; }
        public string Data216 { get; set; }
        public string Data217 { get; set; }
        public string Data218 { get; set; }
        public string Data219 { get; set; }
        public string Data220 { get; set; }
        public string Data221 { get; set; }
        public string Data222 { get; set; }
        public string Data223 { get; set; }
        public string Data224 { get; set; }
        public string Data225 { get; set; }
        public string Data226 { get; set; }
        public string Data227 { get; set; }
        public string Data228 { get; set; }
        public string Data229 { get; set; }
        public string Data230 { get; set; }
        public string Data231 { get; set; }
        public string Data232 { get; set; }
        public string Data233 { get; set; }
        public string Data234 { get; set; }
        public string Data235 { get; set; }
        public string Data236 { get; set; }
        public string Data237 { get; set; }
        public string Data238 { get; set; }
        public string Data239 { get; set; }
        public string Data240 { get; set; }
        public string Data241 { get; set; }
        public string Data242 { get; set; }
        public string Data243 { get; set; }
        public string Data244 { get; set; }
        public string Data245 { get; set; }
        public string Data246 { get; set; }
        public string Data247 { get; set; }
        public string Data248 { get; set; }
        public string Data249 { get; set; }
        public string Data250 { get; set; }
        public string Data251 { get; set; }
        public string Data252 { get; set; }
        public string Data253 { get; set; }
        public string Data254 { get; set; }
        public string Data255 { get; set; }
        public string Data256 { get; set; }
        public string Data257 { get; set; }
        public string Data258 { get; set; }
        public string Data259 { get; set; }
        public string Data260 { get; set; }
        public string Data261 { get; set; }
        public string Data262 { get; set; }
        public string Data263 { get; set; }
        public string Data264 { get; set; }
        public string Data265 { get; set; }
        public string Data266 { get; set; }
        public string Data267 { get; set; }
        public string Data268 { get; set; }
        public string Data269 { get; set; }
        public string Data270 { get; set; }
        public string Data271 { get; set; }
        public string Data272 { get; set; }
        public string Data273 { get; set; }
        public string Data274 { get; set; }
        public string Data275 { get; set; }
        public string Data276 { get; set; }
        public string Data277 { get; set; }
        public string Data278 { get; set; }
        public string Data279 { get; set; }
        public string Data280 { get; set; }
        public string Data281 { get; set; }
        public string Data282 { get; set; }
        public string Data283 { get; set; }
        public string Data284 { get; set; }
        public string Data285 { get; set; }
        public string Data286 { get; set; }
        public string Data287 { get; set; }
        public string Data288 { get; set; }
        public string Data289 { get; set; }
        public string Data290 { get; set; }
        public string Data291 { get; set; }
        public string Data292 { get; set; }
        public string Data293 { get; set; }
        public string Data294 { get; set; }
        public string Data295 { get; set; }
        public string Data296 { get; set; }
        public string Data297 { get; set; }
        public string Data298 { get; set; }
        public string Data299 { get; set; }
        public string Data300 { get; set; }
        public string Data301 { get; set; }
        public string Data302 { get; set; }
        public string Data303 { get; set; }
        public string Data304 { get; set; }
        public string Data305 { get; set; }
        public string Data306 { get; set; }
        public string Data307 { get; set; }
        public string Data308 { get; set; }
        public string Data309 { get; set; }
        public string Data310 { get; set; }
        public string Data311 { get; set; }
        public string Data312 { get; set; }
        public string Data313 { get; set; }
        public string Data314 { get; set; }
        public string Data315 { get; set; }
        public string Data316 { get; set; }
        public string Data317 { get; set; }
        public string Data318 { get; set; }
        public string Data319 { get; set; }
        public string Data320 { get; set; }
        public string Data321 { get; set; }
        public string Data322 { get; set; }
        public string Data323 { get; set; }
        public string Data324 { get; set; }
        public string Data325 { get; set; }
        public string Data326 { get; set; }
        public string Data327 { get; set; }
        public string Data328 { get; set; }
        public string Data329 { get; set; }
        public string Data330 { get; set; }
        public string Data331 { get; set; }
        public string Data332 { get; set; }
        public string Data333 { get; set; }
        public string Data334 { get; set; }
        public string Data335 { get; set; }
        public string Data336 { get; set; }
        public string Data337 { get; set; }
        public string Data338 { get; set; }
        public string Data339 { get; set; }
        public string Data340 { get; set; }
        public string Data341 { get; set; }
        public string Data342 { get; set; }
        public string Data343 { get; set; }
        public string Data344 { get; set; }
        public string Data345 { get; set; }
        public string Data346 { get; set; }
        public string Data347 { get; set; }
        public string Data348 { get; set; }
        public string Data349 { get; set; }
        public string Data350 { get; set; }
        public string Data351 { get; set; }
        public string Data352 { get; set; }
        public string Data353 { get; set; }
        public string Data354 { get; set; }
        public string Data355 { get; set; }
        public string Data356 { get; set; }
        public string Data357 { get; set; }
        public string Data358 { get; set; }
        public string Data359 { get; set; }
        public string Data360 { get; set; }
        public string Data361 { get; set; }
        public string Data362 { get; set; }
        public string Data363 { get; set; }
        public string Data364 { get; set; }
        public string Data365 { get; set; }
        public string Data366 { get; set; }
        public string Data367 { get; set; }
        public string Data368 { get; set; }
        public string Data369 { get; set; }
        public string Data370 { get; set; }
        public string Data371 { get; set; }
        public string Data372 { get; set; }
        public string Data373 { get; set; }
        public string Data374 { get; set; }
        public string Data375 { get; set; }
        public string Data376 { get; set; }
        public string Data377 { get; set; }
        public string Data378 { get; set; }
        public string Data379 { get; set; }
        public string Data380 { get; set; }
        public string Data381 { get; set; }
        public string Data382 { get; set; }
        public string Data383 { get; set; }
        public string Data384 { get; set; }
        public string Data385 { get; set; }
        public string Data386 { get; set; }
        public string Data387 { get; set; }
        public string Data388 { get; set; }
        public string Data389 { get; set; }
        public string Data390 { get; set; }
        public string Data391 { get; set; }
        public string Data392 { get; set; }
        public string Data393 { get; set; }
        public string Data394 { get; set; }
        public string Data395 { get; set; }
        public string Data396 { get; set; }
        public string Data397 { get; set; }
        public string Data398 { get; set; }
        public string Data399 { get; set; }
        public string Data400 { get; set; }
        public string Data401 { get; set; }
        public string Data402 { get; set; }
        public string Data403 { get; set; }
        public string Data404 { get; set; }
        public string Data405 { get; set; }
        public string Data406 { get; set; }
        public string Data407 { get; set; }
        public string Data408 { get; set; }
        public string Data409 { get; set; }
        public string Data410 { get; set; }
        public string Data411 { get; set; }
        public string Data412 { get; set; }
        public string Data413 { get; set; }
        public string Data414 { get; set; }
        public string Data415 { get; set; }
        public string Data416 { get; set; }
        public string Data417 { get; set; }
        public string Data418 { get; set; }
        public string Data419 { get; set; }
        public string Data420 { get; set; }
        public string Data421 { get; set; }
        public string Data422 { get; set; }
        public string Data423 { get; set; }
        public string Data424 { get; set; }
        public string Data425 { get; set; }
        public string Data426 { get; set; }
        public string Data427 { get; set; }
        public string Data428 { get; set; }
        public string Data429 { get; set; }
        public string Data430 { get; set; }
        public string Data431 { get; set; }
        public string Data432 { get; set; }
        public string Data433 { get; set; }
        public string Data434 { get; set; }
        public string Data435 { get; set; }
        public string Data436 { get; set; }
        public string Data437 { get; set; }
        public string Data438 { get; set; }
        public string Data439 { get; set; }
        public string Data440 { get; set; }
        public string Data441 { get; set; }
        public string Data442 { get; set; }
        public string Data443 { get; set; }
        public string Data444 { get; set; }
        public string Data445 { get; set; }
        public string Data446 { get; set; }
        public string Data447 { get; set; }
        public string Data448 { get; set; }
        public string Data449 { get; set; }
        public string Data450 { get; set; }
        public string Data451 { get; set; }
        public string Data452 { get; set; }
        public string Data453 { get; set; }
        public string Data454 { get; set; }
        public string Data455 { get; set; }
        public string Data456 { get; set; }
        public string Data457 { get; set; }
        public string Data458 { get; set; }
        public string Data459 { get; set; }
        public string Data460 { get; set; }
        public string Data461 { get; set; }
        public string Data462 { get; set; }
        public string Data463 { get; set; }
        public string Data464 { get; set; }
        public string Data465 { get; set; }
        public string Data466 { get; set; }
        public string Data467 { get; set; }
        public string Data468 { get; set; }
        public string Data469 { get; set; }
        public string Data470 { get; set; }
        public string Data471 { get; set; }
        public string Data472 { get; set; }
        public string Data473 { get; set; }
        public string Data474 { get; set; }
        public string Data475 { get; set; }
        public string Data476 { get; set; }
        public string Data477 { get; set; }
        public string Data478 { get; set; }
        public string Data479 { get; set; }
        public string Data480 { get; set; }
        public string Data481 { get; set; }
        public string Data482 { get; set; }
        public string Data483 { get; set; }
        public string Data484 { get; set; }
        public string Data485 { get; set; }
        public string Data486 { get; set; }
        public string Data487 { get; set; }
        public string Data488 { get; set; }
        public string Data489 { get; set; }
        public string Data490 { get; set; }
        public string Data491 { get; set; }
        public string Data492 { get; set; }
        public string Data493 { get; set; }
        public string Data494 { get; set; }
        public string Data495 { get; set; }
        public string Data496 { get; set; }
        public string Data497 { get; set; }
        public string Data498 { get; set; }
        public string Data499 { get; set; }
        public string Data500 { get; set; }
        public decimal DcolDataId { get; set; }
    }
}
