using System;
using System.Collections.Generic;

namespace VFDP.Models
{
    public partial class MesDurableMasMv
    {
        public string DurableId { get; set; }
        public string DurableTyp { get; set; }
        public string DurableGrpId { get; set; }
        public string DurableGrpVer { get; set; }
        public string MatlLocCd { get; set; }
        public string TransGrpId { get; set; }
        public double? UseNumcntLimitVal { get; set; }
        public double? UseDurLimitVal { get; set; }
        public double? UseNumcnt { get; set; }
        public double? UseDur { get; set; }
        public decimal? Capa { get; set; }
        public decimal? LotQty { get; set; }
        public string FacId { get; set; }
        public string AreaId { get; set; }
        public string DurableStatCd { get; set; }
        public string DurableCleanStatCd { get; set; }
        public string LastEventCd { get; set; }
        public string LastEventTimekey { get; set; }
        public DateTime? LastEventTm { get; set; }
        public string LastEventUserId { get; set; }
        public string LastEventDesc { get; set; }
        public string LastEventTyp { get; set; }
        public DateTime? CrtTm { get; set; }
        public string CrtUserId { get; set; }
        public string ReasonCatgCd { get; set; }
        public string ReasonCd { get; set; }
        public string ObjId { get; set; }
        public string Rfid { get; set; }
        public string StampId { get; set; }
        public string MatlTyp { get; set; }
        public DateTime? AftCleanUseDurLimitVal { get; set; }
        public double? AftCleanUseNumcntLimitVal { get; set; }
        public double? AftCleanUseDur { get; set; }
        public double? AftCleanUseNumcnt { get; set; }
        public double? CleanNumcntLimitVal { get; set; }
        public double? CleanNumcnt { get; set; }
        public string CleanTyp { get; set; }
        public DateTime? LastCleanTm { get; set; }
        public decimal? InspNumcnt { get; set; }
        public decimal? RepairNumcnt { get; set; }
        public string CarrierCatgCd { get; set; }
        public string SubCatgCd { get; set; }
        public string CarrierColorCd { get; set; }
        public string VendorId { get; set; }
        public string DoorId { get; set; }
        public string LocNm { get; set; }
        public string CarrierId { get; set; }
        public string EqpId { get; set; }
        public string PortNm { get; set; }
        public string SorterId { get; set; }
        public string BatchSeq { get; set; }
        public string WfLoadStatCd { get; set; }
        public string MesStatTyp { get; set; }
        public string MesProcStatCd { get; set; }
        public string GoalStkId { get; set; }
        public string GoalEqpId { get; set; }
        public string GoalPortNm { get; set; }
        public string SorterJobId { get; set; }
        public string ReticleTyp { get; set; }
        public string ConfEngrUserId1 { get; set; }
        public string ConfEngrUserId2 { get; set; }
        public string ConfEngrUserId3 { get; set; }
        public string ConfEngrUserId4 { get; set; }
        public string ConfDesc1 { get; set; }
        public string ConfDesc2 { get; set; }
        public string ConfDesc3 { get; set; }
        public string ConfDesc4 { get; set; }
        public string ConfYn { get; set; }
        public string ResvFieldVal1 { get; set; }
        public string ResvFieldVal2 { get; set; }
        public string ResvFieldVal3 { get; set; }
        public string ResvFieldVal4 { get; set; }
        public string ResvFieldVal5 { get; set; }
        public string EmcBayNm { get; set; }
        public string EmcEqpGrpId { get; set; }
        public string EmcEqpId { get; set; }
        public string MoveStatCd { get; set; }
        public string LastLotBatchId { get; set; }
        public DateTime? StkKeepTm { get; set; }
        public string SlotMapEqpId { get; set; }
        public string LotCd { get; set; }
        public string RefLotId { get; set; }
        public string IrisStatTyp { get; set; }
        public string ReticleParticleCnt1 { get; set; }
        public string ReticleParticleCnt2 { get; set; }
        public string LastIrisActivaTm { get; set; }
        public string DurableEventDesc { get; set; }
        public string CidVerifyRsltVal { get; set; }
        public string UnloadPortNm { get; set; }
        public string MonMoveoutTimekey { get; set; }
        public string FrFabId { get; set; }
        public decimal? UseCnt { get; set; }
        public decimal? UseLimitVal { get; set; }
        public decimal? RecycNumcnt { get; set; }
        public decimal? RecycNumcntLimitVal { get; set; }
        public string DiscardTm { get; set; }
        public string DurableCatgCd { get; set; }
        public string OrgFabId { get; set; }
        public string FamilyCd { get; set; }
    }
}
