using System;
using System.Collections.Generic;

namespace VFDP.Models
{
    public partial class MesEqpMasMv
    {
        public string EqpId { get; set; }
        public string EqpTyp { get; set; }
        public string DetEqpTyp { get; set; }
        public string CtnDesc { get; set; }
        public string FacId { get; set; }
        public string AreaId { get; set; }
        public string UpperEqpId { get; set; }
        public string EqpGrpId { get; set; }
        public string VendorNm { get; set; }
        public string ModelTyp { get; set; }
        public string SerialNo { get; set; }
        public string ProcUnitCd { get; set; }
        public decimal? ProcCapa { get; set; }
        public decimal? LotBatchMinSize { get; set; }
        public decimal? LotBatchMaxSize { get; set; }
        public string DefaultRecipeNspaceCd { get; set; }
        public string EqpStatModelCd { get; set; }
        public decimal? LoadCapa { get; set; }
        public string EqpModelCd { get; set; }
        public string EapEqpModelCd { get; set; }
        public string DefaultStkId { get; set; }
        public string DefaultStkPortNm { get; set; }
        public string DefaultEapNm { get; set; }
        public string StructTyp { get; set; }
        public string LogicalChambId { get; set; }
        public string ResrcTyp { get; set; }
        public string CrtMonLotYn { get; set; }
        public string RootAreaId { get; set; }
        public string BayNm { get; set; }
        public string ObjId { get; set; }
        public string RootEqpId { get; set; }
        public string RootObjId { get; set; }
        public DateTime? CrtTm { get; set; }
        public string CrtUserId { get; set; }
        public DateTime? ChgTm { get; set; }
        public string ChgUserId { get; set; }
        public string ResrcDedicTyp { get; set; }
        public string ResrcGrpNm { get; set; }
        public string TrackTyp { get; set; }
        public string SubEqpTyp { get; set; }
        public decimal? EnableBuffSize { get; set; }
        public string RmsItgYn { get; set; }
        public string SorterItgYn { get; set; }
        public string ResvFieldVal1 { get; set; }
        public string OnlineTgtTyp { get; set; }
        public string SpcTgtYn { get; set; }
        public string SpcYn { get; set; }
        public string FdcTgtYn { get; set; }
        public string FdcIngotYn { get; set; }
        public string BatchSeqRuleTyp { get; set; }
        public string PjRuleVal { get; set; }
        public string FdcMainGrpNm { get; set; }
        public string FdcEqpGrpId { get; set; }
        public string RecipeParaChkYn { get; set; }
        public string EnablePrcsYn { get; set; }
        public string TransferTyp { get; set; }
        public string AutoR2rYn { get; set; }
        public string ZoneNm { get; set; }
        public string OperRuleDesc { get; set; }
        public string StartQueueTyp { get; set; }
        public string QTmChkYn { get; set; }
        public decimal? QTmIntval { get; set; }
        public string SdptNm { get; set; }
        public string MgmtAreaId { get; set; }
        public string JobPrepCapa { get; set; }
        public string RetransmitPortNm { get; set; }
        public string DcolIntlockYn { get; set; }
        public string RtdItgYn { get; set; }
        public string DspRuleTyp { get; set; }
        public string JobPrepTyp { get; set; }
        public string ShiftIntlockRuleCd { get; set; }
        public string Photo1ClickYn { get; set; }
        public string MetalTyp { get; set; }
        public string JobPrepEesMsgTyp { get; set; }
        public string OwnerNm { get; set; }
        public string PreArranSupplyOptVal { get; set; }
        public string BatchLoadRuleTyp { get; set; }
        public string R2rItgYn { get; set; }
        public string ChkRecipeYn { get; set; }
        public string PadBreakInIntlockCd { get; set; }
        public string McsItgYn { get; set; }
        public string TibSubjNm { get; set; }
        public string SopItgYn { get; set; }
        public string NonClickYn { get; set; }
        public string EqvMstCd { get; set; }
        public string SiteCd { get; set; }
        public string BuildingNm { get; set; }
        public string FloorNm { get; set; }
        public string EqpVer { get; set; }
        public string PpmIngotYn { get; set; }
        public decimal? EnableBuffMinSize { get; set; }
        public string MultiRecipeYn { get; set; }
        public decimal? DailyMaxCapa { get; set; }
        public string NonNoResvYn { get; set; }
        public string CertTyp { get; set; }
        public string ReticleChgIntlockCd { get; set; }
        public string SpecialEqpTyp { get; set; }
        public string EqpOperGrpCd { get; set; }
        public string MetalYn { get; set; }
        public string MultiRackYn { get; set; }
        public string CuYn { get; set; }
        public string ContamYn { get; set; }
        public string ChuckDedicYn { get; set; }
        public string MtjYn { get; set; }
        public string DefaultUtsNm { get; set; }
        public string UseWhereNextYn1 { get; set; }
        public string NextRuleWhereCd1 { get; set; }
        public string UseWhereNextYn2 { get; set; }
        public string NextRuleWhereCd2 { get; set; }
        public string UseWhereNextYn3 { get; set; }
        public string NextRuleWhereCd3 { get; set; }
        public string MsResvAttrVal1 { get; set; }
        public string MsResvAttrVal2 { get; set; }
        public string MsResvAttrVal3 { get; set; }
        public string MsResvAttrVal4 { get; set; }
        public string MsResvAttrVal5 { get; set; }
        public string MsResvAttrVal6 { get; set; }
        public string MsResvAttrVal7 { get; set; }
        public string MsResvAttrVal8 { get; set; }
        public string MsResvAttrVal9 { get; set; }
        public string MsResvAttrVal10 { get; set; }
    }
}
