using System;
using System.Collections.Generic;

namespace VFDP.Models
{
    public partial class MesLotMasMv
    {
        public string LotId { get; set; }
        public string ProduceTyp { get; set; }
        public string ProdId { get; set; }
        public string ProdVer { get; set; }
        public string ProdId2 { get; set; }
        public string ProdVer2 { get; set; }
        public string LotBatchId { get; set; }
        public string ProdReqId { get; set; }
        public string OrgLotId { get; set; }
        public string SrcLotId { get; set; }
        public string GoalLotId { get; set; }
        public string RootLotId { get; set; }
        public string ParentLotId { get; set; }
        public string CarrierId { get; set; }
        public string ProdTyp { get; set; }
        public string SubProdTyp { get; set; }
        public decimal? SubProdUnitQty1 { get; set; }
        public decimal? SubProdUnitQty2 { get; set; }
        public decimal? CrtWfQty { get; set; }
        public decimal? CrtSubProdQty { get; set; }
        public decimal? CrtSubProdQty1 { get; set; }
        public decimal? CrtSubProdQty2 { get; set; }
        public decimal? WfQty { get; set; }
        public decimal? SubProdQty { get; set; }
        public decimal? SubProdQty1 { get; set; }
        public decimal? SubProdQty2 { get; set; }
        public string LotGradeTyp { get; set; }
        public DateTime? DueTm { get; set; }
        public decimal? Priority { get; set; }
        public string FacId { get; set; }
        public string TgtFacId { get; set; }
        public string AreaId { get; set; }
        public string LotStatTyp { get; set; }
        public string LotProcStatCd { get; set; }
        public string LotHoldStatCd { get; set; }
        public string LastEventCd { get; set; }
        public string LastEventTimekey { get; set; }
        public DateTime? LastEventTm { get; set; }
        public string LastEventUserId { get; set; }
        public string LastEventDesc { get; set; }
        public string LastEventTyp { get; set; }
        public DateTime? CrtTm { get; set; }
        public string CrtUserId { get; set; }
        public DateTime? ReleaseTm { get; set; }
        public string ReleaseUserId { get; set; }
        public DateTime? LastMoveinTm { get; set; }
        public string LastMoveinUserId { get; set; }
        public DateTime? LastMoveoutTm { get; set; }
        public string LastMoveoutUserId { get; set; }
        public string ReasonCatgCd { get; set; }
        public string ReasonCd { get; set; }
        public string FlowId { get; set; }
        public string FlowVer { get; set; }
        public string OperId { get; set; }
        public string OperVer { get; set; }
        public string NodeStackVal { get; set; }
        public string EqpId { get; set; }
        public string EqpRecipeId { get; set; }
        public string RwkStatCd { get; set; }
        public decimal? RwkCnt { get; set; }
        public string RwkNodeId { get; set; }
        public string HotTyp { get; set; }
        public string OwnerCd { get; set; }
        public string CrtCd { get; set; }
        public DateTime? InTm { get; set; }
        public decimal? CycleTime { get; set; }
        public string EqpGrpId { get; set; }
        public string StkId { get; set; }
        public string RecipeNspaceCd { get; set; }
        public string ReticleFamilyCd { get; set; }
        public string ReticleId { get; set; }
        public string PortNm { get; set; }
        public string InQueueTimeTyp { get; set; }
        public DateTime? QueueStartTm { get; set; }
        public string LastStepperNm { get; set; }
        public string ResvStepperNm { get; set; }
        public string ResvTrackNm { get; set; }
        public string StepperRecipeId { get; set; }
        public string MesProcStatCd { get; set; }
        public string SubAreaId { get; set; }
        public string CapaCd { get; set; }
        public string ShipCd { get; set; }
        public string ShipCancelUserId { get; set; }
        public string ShipCancelPartNm { get; set; }
        public string ShipCancelReasonTyp { get; set; }
        public string ShipCancelTyp { get; set; }
        public string ObjId { get; set; }
        public string RwkReturnFlowId { get; set; }
        public string RwkReturnOperId { get; set; }
        public string MergeFlowId { get; set; }
        public string MergeOperId { get; set; }
        public string MergeId { get; set; }
        public string MonJobId { get; set; }
        public decimal? MonRecycNumcnt { get; set; }
        public decimal? UseWfCnt { get; set; }
        public string MainLotId { get; set; }
        public string LotEventDesc { get; set; }
        public string SampLotYn { get; set; }
        public string ResvEqpId { get; set; }
        public string GoalStkId { get; set; }
        public string GoalEqpId { get; set; }
        public string GoalPortNm { get; set; }
        public string DelHistYn { get; set; }
        public string LastEqpId { get; set; }
        public string LastTrackNm { get; set; }
        public string LastEqpRecipeId { get; set; }
        public string LastStepperRecipeId { get; set; }
        public DateTime? LastJobPrepTm { get; set; }
        public string MonStatTyp { get; set; }
        public string MainEqpId { get; set; }
        public string ProcSubEqpId { get; set; }
        public DateTime? FabOutDueTm { get; set; }
        public string MainFlowId { get; set; }
        public string MainOperId { get; set; }
        public string EngrUserId { get; set; }
        public string ResvFieldVal1 { get; set; }
        public string ResvFieldVal2 { get; set; }
        public string ResvFieldVal3 { get; set; }
        public string ResvFieldVal4 { get; set; }
        public string ResvFieldVal5 { get; set; }
        public string ResvFieldVal6 { get; set; }
        public string ResvFieldVal7 { get; set; }
        public string ResvFieldVal8 { get; set; }
        public string ResvFieldVal9 { get; set; }
        public string ResvFieldVal10 { get; set; }
        public string DummyQty { get; set; }
        public string RwkMainFlowId { get; set; }
        public string RwkMainOperId { get; set; }
        public string NextResvEqpId { get; set; }
        public string ChkListTyp { get; set; }
        public string NpwBayNm { get; set; }
        public string NpwEqpGrpId { get; set; }
        public decimal? SubQty1 { get; set; }
        public decimal? SubQty2 { get; set; }
        public decimal? SubQty3 { get; set; }
        public decimal? SubQty4 { get; set; }
        public decimal? SubTotQty { get; set; }
        public decimal? WfQty2 { get; set; }
        public string ShipApproveUserId { get; set; }
        public string ReturnReasonTyp { get; set; }
        public string ShipGradeCd { get; set; }
        public string ShipSwrNm { get; set; }
        public string MainEventTm { get; set; }
        public string SrcMonUseTyp { get; set; }
        public string StepperStartYn { get; set; }
        public string LastReticleId { get; set; }
        public string LastPortNm { get; set; }
        public string LastSampLotId { get; set; }
        public string LastSampCarrierId { get; set; }
        public string LastSampSlotNo { get; set; }
        public string EqpJobEventTyp { get; set; }
        public string MeasMainFlowId { get; set; }
        public string MeasMainOperId { get; set; }
        public string MeasMainEqpId { get; set; }
        public string ProcChgLotId { get; set; }
        public string RwkReturnYn { get; set; }
        public string ReticleProdId { get; set; }
        public string ReticleFlowId { get; set; }
        public string ReticleOperId { get; set; }
        public string MeasCompltTyp { get; set; }
        public string MoveProdYn { get; set; }
        public string DedicId { get; set; }
        public string HotTypFrOperId { get; set; }
        public string RwkReturnOperYn { get; set; }
        public string MoveFabId { get; set; }
        public string MfgNationNm { get; set; }
        public string MfgCompnyNm { get; set; }
        public string AlarmHoldYn { get; set; }
        public string AutoR2rYn { get; set; }
        public string ResvAlarmYn { get; set; }
        public DateTime? LoadTm { get; set; }
        public string NextResvRecipeId { get; set; }
        public string ResvRecipeId { get; set; }
        public string JobSlotInfoVal { get; set; }
        public DateTime? FrOutFabInTm { get; set; }
        public string HotLotReleaseOperId { get; set; }
        public string PhotoStatTyp { get; set; }
        public string TransferPauseYn { get; set; }
        public string ReticleVer { get; set; }
        public string LastLocEqpId { get; set; }
        public string CustNm { get; set; }
        public string SapCd { get; set; }
        public string PhotoSampLotId { get; set; }
        public string ShipPrintYn { get; set; }
        public DateTime? MainMoveinTm { get; set; }
        public DateTime? MainMoveoutTm { get; set; }
        public string ArrvVal { get; set; }
        public string PcbankYn { get; set; }
        public string DervReturnFlowId { get; set; }
        public string DervReturnOperId { get; set; }
        public string BatchIntlockOperId { get; set; }
        public string FirstFlowPrintVal { get; set; }
        public string BatchZoneNm { get; set; }
        public string MainEqpRecipeId { get; set; }
        public DateTime? SendCmdTm { get; set; }
        public string CautCtn { get; set; }
        public string CancelCd { get; set; }
        public string ProdRecipeYn { get; set; }
        public string BatchZoneSeq { get; set; }
        public DateTime? ResvEqpTm { get; set; }
        public string PrbTestYn { get; set; }
        public string FrFabId { get; set; }
        public string MoveFlowYn { get; set; }
        public string FabId { get; set; }
        public decimal? ResvSeq { get; set; }
        public decimal? SampSeq { get; set; }
        public string PmsYn { get; set; }
        public string ResvAttrVal1 { get; set; }
        public string ResvAttrVal2 { get; set; }
        public string ResvAttrVal3 { get; set; }
        public string ResvAttrVal4 { get; set; }
        public string ResvAttrVal5 { get; set; }
        public string ResvAttrVal6 { get; set; }
        public string ResvAttrVal7 { get; set; }
        public string ResvAttrVal8 { get; set; }
        public string ResvAttrVal9 { get; set; }
        public string ResvAttrVal10 { get; set; }
    }
}
